name: food_recipe_final
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  provider: ^6.0.0
  flutter_colorpicker: ^0.6.0
  intl: ^0.17.0
  uuid: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  flutter_svg: ^1.1.0
  json_annotation: ^4.6.0
  http: ^0.13.4
  cached_network_image: ^3.1.0
  flutter_slidable: ^0.6.0
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  firebase_storage: ^10.3.4
  firebase_auth: ^3.6.1
  image_picker: ^0.8.5+3
  dartz: ^0.10.1
  get: ^4.6.5
  bubble: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  websafe_svg: ^2.1.2+2
  flutter_native_splash: ^2.2.8
  dropdown_button2: ^1.7.2
  flutter_localizations:
    sdk: flutter
 


  # sqflite: ^2.0.3+1
  # path_provider: ^2.0.11
  # sqlbrite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_launcher_icons: ^0.10.0
  build_runner: ^2.1.1
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#eeeeee"
  image: assets/app_logo.png
  color_dark: "#232220"
  image_dark: assets/app_logo.png
  android: true
  ios: true
flutter_icons:
  # android: true
  # ios: true
  # image_path: "assets/app_logo.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - assets/images/
    - assets/onboarding/
    - assets/onboarding/pages/
    - assets/
    - assets/food/feature/
    - assets/food/today/
    - assets/food/popular/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: google_fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
